version: 3

tasks:
  default: task -a

  top-go:
    cmds:
      - |
        uv run python main.py \
          --language go \
          --min-stars 25000 \
          --max-stars 40000 \
          --output top-go-projects.csv

  top-python:
    cmds:
      - |
        uv run python main.py \
          --language python \
          --min-stars 25000 \
          --max-stars 40000 \
          --output top-python-projects.csv

  list:
    cmds:
      - |
        mlr --from github_repos.csv --c2p --barred cat

  go-view:
    cmds:
      - |
        tw top-go-projects.csv

  python-view:
    cmds:
      - |
        tw top-go-projects.csv
