version: 3

tasks:
  default: task -a

  top-go:
    cmds:
      - |
        out="top-go-projects.csv"
        if [[ -f ${out} ]] ; then
          echo "file ${out} already exist. Delete file to regenerate."
          exit
        fi

        uv run python main.py \
          --language go \
          --min-stars 25000 \
          --max-stars 40000 \
          --output ${out}

  top-python:
    cmds:
      - |
        out="top-python-projects.csv"
        if [[ -f ${out} ]] ; then
          echo "file ${out} already exist. Delete file to regenerate."
          exit
        fi

        uv run python main.py \
          --language python \
          --min-stars 25000 \
          --max-stars 40000 \
          --output ${out}

  go-view:
    cmds:
      - |
        tw top-go-projects.csv

  python-view:
    cmds:
      - |
        tw top-go-projects.csv
